import type { Vehicle } from "@/types/vehicle";

/**
 * Proton All-New Saga (MC3, 2025). Copy, specifications, prices and paint
 * swatches are taken from proton.com/models/all-new-saga (used with Proton's
 * permission).
 *
 * 3D MODEL: public/models/proton-saga.glb is a STYLISED STAND-IN generated by
 * `npm run generate:sedan` (scripts/generate-sedan.mjs) to the Saga's rough
 * proportions — not an accurate replica. Replace the file with the real model
 * when available, then re-check `meshMapping`, feature `meshNames`/positions
 * and cameras with `npm run inspect:model` and `?debug=vehicle`.
 *
 * World space: metres, ground at y = 0, nose towards +Z, left side towards +X.
 */
export const protonSaga: Vehicle = {
  id: "proton-saga",
  name: "Proton Saga",
  subtitle: "All-New Saga · i-GT 1.5 Sedan",
  tags: ["Sedan", "i-GT 1.5", "Premium"],
  startingPrice: "RM38,990",

  model: {
    url: "/models/proton-saga.glb",
    dracoDecoderPath: "/draco/",
    transform: {
      position: [0, 0, 0],
      rotation: [0, 0, 0],
      scale: 1,
      normalize: true,
    },
    // Names from `npm run inspect:model public/models/proton-saga.glb`
    // (generated by scripts/generate-sedan.mjs).
    meshMapping: {
      body: { materials: ["Paint"] },
      glass: { materials: ["Glass"] },
      tyres: { materials: ["Tyre"] },
      // "Rim_Silver" (machined alloy) is left unmapped: its satin finish reads bright.
      brakes: { materials: ["Brake"] },
      headlights: { materials: ["Headlight", "DRL"] },
      taillights: { materials: ["TailLight", "TailLight_Smoked"] },
      // "Lettering" (rear badges) is left unmapped: its own satin silver reads best.
      chrome: { materials: ["Chrome"] },
      trim: { materials: ["Trim_Black", "Trim_Gloss", "Rim_Dark"] },
      interior: { materials: ["Interior_*", "Headliner", "Screen"] },
    },
    orbit: {
      fov: 32,
      minDistance: 3.8,
      maxDistance: 11,
      minPolarAngle: 0.8,
      maxPolarAngle: 1.48,
    },
  },

  // Swatch colours as shown on Proton's colours page. Confirm exact paint values with Proton.
  colors: [
    { id: "marine-blue", name: "Marine Blue", hex: "#125488", finish: "metallic" },
    { id: "silver", name: "Silver", hex: "#575e71", finish: "metallic" },
    { id: "ruby-red", name: "Ruby Red", hex: "#ab271a", finish: "metallic" },
  ],
  defaultColorId: "marine-blue",

  navSpecGroupIds: ["performance", "technology", "safety"],

  specifications: [
    {
      id: "overview",
      title: "Overview",
      items: [
        { id: "body", label: "Body Style", value: "4-Door Sedan" },
        { id: "engine", label: "Engine", value: "i-GT 1.5", highlight: true },
        { id: "warranty", label: "Warranty", value: "5 years or 150,000 km" },
        { id: "service", label: "Free Labour Service", value: "3 times" },
      ],
    },
    {
      id: "performance",
      title: "Performance",
      items: [
        { id: "engine-type", label: "Engine", value: "All-New i-GT 1.5" },
        { id: "power", label: "Maximum Power", value: "120 PS", highlight: true },
        { id: "torque", label: "Maximum Torque", value: "150 Nm", highlight: true },
        { id: "timing", label: "Timing System", value: "Toothed timing chain, 25.24% quieter" },
        { id: "steering", label: "Steering", value: "Electric Power Steering (EPS)" },
      ],
    },
    {
      id: "safety",
      title: "Safety",
      items: [
        { id: "airbags", label: "Airbags", value: "6 SRS airbags", highlight: true },
        { id: "aeb", label: "Collision Avoidance", value: "AEB with Forward Collision Warning" },
        { id: "lane", label: "Lane Support", value: "Lane Departure Warning, Lane Change Assist" },
        { id: "rear", label: "Rear Assistance", value: "Rear Cross Traffic Alert, Rear Collision Warning" },
        { id: "dow", label: "Door Opening Warning", value: "Audio and visual alerts" },
        { id: "structure", label: "Body Structure", value: "PROTON RESS, up to 1,500 MPa" },
        { id: "parking", label: "Parking", value: "Front and rear sensors, reverse camera" },
      ],
    },
    {
      id: "technology",
      title: "Technology",
      items: [
        { id: "screens", label: "Integrated Dual Screen", value: "16\" (7\" digital meter + 9\" infotainment)" },
        { id: "phone", label: "Smartphone", value: "Wireless Apple CarPlay & Android Auto" },
        { id: "entry", label: "Entry & Start", value: "Intelligent entry with push start" },
        { id: "usb", label: "USB Ports", value: "3" },
        { id: "headlamps", label: "Headlamps", value: "Auto on/off, follow-me-home, levelling" },
        { id: "high-beam", label: "High Beam", value: "Intelligent High Beam Control" },
      ],
    },
    {
      id: "exterior",
      title: "Exterior",
      items: [
        { id: "headlamps", label: "Headlamps", value: "Full LED projector with DRL" },
        { id: "grille", label: "Grille", value: "'Sulaman Songket' design" },
        { id: "wheels", label: "Wheels", value: "Dual-tone 15\" 'Arrow' alloys" },
        { id: "rear-lamps", label: "Rear Lamps", value: "Full LED with tail light bar" },
        { id: "mirrors", label: "Door Mirrors", value: "Electric, auto fold" },
        { id: "antenna", label: "Antenna", value: "Shark fin" },
      ],
    },
    {
      id: "interior",
      title: "Interior",
      items: [
        { id: "steering", label: "Steering Wheel", value: "Sporty flat-bottom" },
        { id: "seats", label: "Seats", value: "Dual-tone leatherette" },
        { id: "vents", label: "Air Vents", value: "'Congkak' design" },
        { id: "trim", label: "Door & Dash Trim", value: "'Pantai' wave design" },
        { id: "cooling", label: "Air Conditioning", value: "Coolest cabin in segment (15.2°C)" },
        { id: "headrests", label: "Rear Headrests", value: "Adjustable" },
      ],
    },
  ],

  // On-car hotspots are added once the GLB has been inspected (they need measured positions).
  features: [
    {
      id: "headlights",
      shortTitle: "Headlamps",
      title: "Full LED Projector Headlamps",
      category: "Exterior",
      description:
        "Full LED projector headlamps with Daytime Running Lamps illuminate every journey with a signature presence that stands out day and night.",
      highlights: ["Auto on/off", "Follow-me-home lights", "Headlamp levelling"],
      meshNames: ["Headlight_*", "DRL_*"],
      camera: { position: [2.4, 1.2, 4.5], target: [0.4, 0.65, 1.8] },
      callout: { anchor: [0.64, 0.74, 2.02], elbow: [1.0, 1.15, 2.35], label: [1.5, 1.15, 2.35] },
      toggle: { label: "Headlamps", onLabel: "On", offLabel: "Off", emissive: { color: "#f2f7ff", intensity: 4 } },
    },
    {
      id: "grille",
      shortTitle: "Grille",
      title: "'Sulaman Songket' Grille",
      category: "Design",
      description: "A refined expression of Malaysian artistry, woven into every drive.",
      highlights: ["Songket-inspired pattern", "Chrome signature wing", "Gloss black finish"],
      meshNames: ["Grille", "Grille_Chrome", "Grille_Pattern", "Badge", "Front_Plate*"],
      camera: { position: [-1.2, 1.0, 5.0], target: [0, 0.5, 1.9] },
      callout: { anchor: [0.3, 0.55, 2.1], elbow: [-0.35, 0.28, 2.7], label: [-0.65, 0.28, 3.0] },
    },
    {
      id: "wheels",
      shortTitle: "Wheel",
      title: "Dual-Tone 15\" Alloy Wheels",
      category: "Exterior",
      description: "Command attention with the new directional 'Arrow' alloy wheels, finished in an elegant two-tone design.",
      highlights: ["Directional 'Arrow' design", "Two-tone finish", "185/55 R15 tyres"],
      meshNames: ["Tyre_*", "Rim*", "Brake_*"],
      camera: { position: [4.2, 0.9, 2.8], target: [0.7, 0.35, 1.1] },
      callout: { anchor: [0.84, 0.29, 1.318], elbow: [1.3, 0.85, 1.65], label: [1.8, 0.85, 1.65] },
    },
    {
      id: "mirrors",
      shortTitle: "Side Mirror",
      title: "Electric Mirrors with Auto Fold",
      category: "Convenience",
      description: "The door mirrors fold in automatically when you lock the car, for added convenience.",
      highlights: ["Electric adjustment", "Auto fold on locking", "Body-coloured caps"],
      meshNames: ["Mirror_*"],
      camera: { position: [3.4, 1.7, 2.9], target: [0.8, 0.98, 0.7] },
      callout: { anchor: [0.9, 1.05, 0.72], elbow: [1.35, 1.45, 0.95], label: [1.85, 1.45, 0.95] },
    },
    {
      id: "front-doors",
      shortTitle: "Front Doors",
      title: "Front Doors",
      category: "Safety",
      description:
        "Door Opening Warning reduces the risk of accidents when opening the door, with audio alerts and warning lights. Tap to open or close.",
      highlights: ["Door Opening Warning", "Intelligent entry", "RESS body up to 1,500 MPa"],
      meshNames: ["Door_F*"],
      camera: { position: [4.4, 1.6, 2.8], target: [0.4, 0.7, 0] },
      callout: { anchor: [0.87, 0.62, 0.3], elbow: [1.35, 1.05, 0.55], label: [1.85, 1.05, 0.55] },
      toggle: {
        label: "Doors",
        onLabel: "Open",
        offLabel: "Closed",
        animate: [
          { node: "Door_FL", axis: "y", angle: -1.05 },
          { node: "Door_FR", axis: "y", angle: 1.05 },
        ],
      },
    },
    {
      id: "rear-doors",
      shortTitle: "Rear Doors",
      title: "Rear Doors",
      category: "Comfort",
      description: "Wide-opening rear doors give easy access to the rear seats, with adjustable rear headrests.",
      highlights: ["Rear adjustable headrests", "Door Opening Warning", "Child-safety locks"],
      meshNames: ["Door_R*"],
      camera: { position: [4.2, 1.6, -2.6], target: [0.4, 0.7, -0.75] },
      callout: { anchor: [0.87, 0.66, -0.75], elbow: [1.35, 1.1, -1.0], label: [1.85, 1.1, -1.0] },
      toggle: {
        label: "Doors",
        onLabel: "Open",
        offLabel: "Closed",
        animate: [
          { node: "Door_RL", axis: "y", angle: -1.0 },
          { node: "Door_RR", axis: "y", angle: 1.0 },
        ],
      },
    },
    {
      id: "rear-lamps",
      shortTitle: "Rear Lights",
      title: "Full LED Rear Lamps & Light Bar",
      category: "Exterior",
      description:
        "Full LED rear combination lamps and a full-width tail light bar give a refined, futuristic presence on the road.",
      highlights: ["Full-width LED bar", "LED combination lamps", "Rear Collision Warning"],
      meshNames: ["TailLight_*"],
      camera: { position: [-2.4, 1.4, -4.6], target: [-0.3, 0.8, -1.8] },
      callout: { anchor: [-0.68, 0.87, -2.08], elbow: [-1.1, 1.3, -2.4], label: [-1.6, 1.3, -2.4] },
    },
    {
      id: "steering",
      shortTitle: "Steering Wheel",
      title: "Sporty Flat-Bottom Steering",
      category: "Interior",
      description: "A new flat-bottom steering wheel for sporty, driver-focused comfort and convenience.",
      highlights: ["Flat-bottom design", "Multi-function controls", "Electric Power Steering"],
      meshNames: ["Steering_*"],
      viewMode: "interior",
      camera: { position: [-0.22, 1.15, -0.2], target: [-0.37, 0.94, 0.33] },
      callout: { anchor: [-0.37, 0.97, 0.33], elbow: [-0.2, 1.1, 0.42], label: [0.05, 1.1, 0.46] },
    },
    {
      id: "screens",
      shortTitle: "Dual Screen",
      title: "16\" Integrated Dual Screen",
      category: "Technology",
      description:
        "A 7\" digital meter and 9\" infotainment screen with wireless Apple CarPlay and Android Auto.",
      highlights: ["Wireless Apple CarPlay & Android Auto", "7\" digital meter", "9\" infotainment"],
      meshNames: ["Screen_*"],
      viewMode: "interior",
      camera: { position: [0.05, 1.2, -0.08], target: [-0.1, 1.02, 0.52] },
      callout: { anchor: [0.03, 1.1, 0.5], elbow: [0.2, 1.22, 0.42], label: [0.4, 1.22, 0.42] },
    },
    {
      id: "seats",
      shortTitle: "Seats",
      title: "Dual-Tone Leatherette Seats",
      category: "Interior",
      description: "Luxurious comfort meets contemporary design, curated to suit your unique preferences.",
      highlights: ["Dual-tone leatherette", "Rear adjustable headrests", "'Pantai' wave door trim"],
      meshNames: ["Seat_*"],
      viewMode: "interior",
      camera: { position: [-0.05, 1.2, 0.2], target: [0.25, 0.85, -0.45] },
      callout: { anchor: [0.37, 0.98, -0.37], elbow: [0.2, 1.15, -0.5], label: [0, 1.15, -0.55] },
    },
  ],

  cameraPresets: [
    { id: "default", label: "Default", position: [4.4, 1.8, 5.2], target: [0, 0.65, 0] },
    { id: "front", label: "Front", position: [0, 1.3, 6.2], target: [0, 0.7, 0] },
    { id: "rear", label: "Rear", position: [0, 1.3, -6.2], target: [0, 0.7, 0] },
    { id: "left", label: "Left", position: [6.4, 1.2, 0], target: [0, 0.7, 0] },
    { id: "right", label: "Right", position: [-6.4, 1.2, 0], target: [0, 0.7, 0] },
    { id: "three-quarter", label: "Three Quarter", position: [-3.8, 1.3, 4.2], target: [0, 0.6, 0.1] },
  ],
  defaultCameraPresetId: "default",

  viewModes: [
    { id: "exterior", label: "Exterior", available: true },
    {
      id: "interior",
      label: "Interior",
      available: true,
      // Inside the cabin (the Saga has a roof): behind the front seats, looking
      // forward. The camera orbits a point just ahead of it, so dragging looks around.
      camera: { position: [0.02, 1.3, -0.8], target: [-0.05, 1.08, -0.3] },
      orbit: {
        // Wide lens inside the cabin.
        fov: 68,
        minDistance: 0.25,
        maxDistance: 0.85,
        minPolarAngle: 1.05,
        maxPolarAngle: 2.0,
        // Camera stays behind its target (±75°), so the view never leaves the cabin.
        minAzimuthAngle: Math.PI - 1.3,
        maxAzimuthAngle: -(Math.PI - 1.3),
      },
      hint: "Drag to look around the cabin",
    },
  ],

  modelCredit: {
    text: "Proton Saga 3D model is a stylised stand-in for this demo, not an exact replica.",
  },
};
